### ISSUE TITLE
Error related to flatten_rgba

### ISSUE THREAD

**Issue by lrry1126** [roth-hex-lab/Multi-Layer-Anatomy-GS-Training#1]
Hi, I am trying to run the train.py, but the following error appears on all your datasets (different layers of CT). Since this function is new to the original gaussian splatting repo. Could you help me with this error? Thanks in advance!

Traceback (most recent call last):
  File "train.py", line 299, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.save_layer, args.load_layer)
  File "train.py", line 117, in training
    gt_image = flatten_rgba(viewpoint_cam, bg.to("cpu")).cuda()
  File "/home/lry/MLGS/GS-Training/utils/image_utils.py", line 24, in flatten_rgba
    return gt_img_rgba[:3, :, :] * gt_img_rgba[3:4, :, :] + bg_shaped * (1 - gt_img_rgba[3:4, :, :])
TypeError: 'NoneType' object is not subscriptable

**Comment by ninjamode** [comment]
What training data are you using? How did you call training?
I believe this error might show up when trying to flatten the alpha channel with images that dont have one. Do you use rgba pngs?

**Comment by manu15sd** [comment]
It happens to me the same way and I'm using your data without any modifications. I did some debugging and I found out that the problem was that the cam loaded in the training had an attribute called original_image_rgba where it should be the tensor representing the image but it was empty. 

This empty image when looking in the directory happens to be an image with only transparency, no image. I wonder if the authors can shed any light on this, if maybe they removed these images in a later process or how they did it to train the model with the original data.

**Comment by ninjamode** [comment]
Yes, we removed completely transparent images. These would also produce invalid result metrics later (NaN PSNR i believe). Patching the project to support these should be straightforward though, but it was not a priority for me.
